// src/components/Icons.tsx

import {
  faHeart,
  faUser,
  faHouse,
  faBars,
  faUsers,
  faBackward,
  faForward,
  faPlay,
  faPause,
  faImage,
  faAngleDown,
  faAngleRight,
  faVolumeHigh,
  faList,
  faVolumeXmark,
  faVolumeLow,
  faShuffle,
  faShareFromSquare,
  faTrash,
  faArrowUp,
  faCircleCheck,
  faCircleXmark,
  faMagnifyingGlass,
  faPlus,
  faPenToSquare,
  faTriangleExclamation,
  faArrowLeft,
  faCircleExclamation,
  faCircleNotch,
} from "@fortawesome/free-solid-svg-icons";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { FontAwesomeIconProps } from "@fortawesome/react-fontawesome";

type IconProps = Omit<FontAwesomeIconProps, "icon">;

export const Icons = {
  Menu: (props?: IconProps) => <FontAwesomeIcon icon={faBars} {...props} />,
  Home: (props?: IconProps) => <FontAwesomeIcon icon={faHouse} {...props} />,
  Fav: (props?: IconProps) => <FontAwesomeIcon icon={faHeart} {...props} />,
  Heart: (props?: IconProps) => <FontAwesomeIcon icon={faHeart} {...props} />,
  Subs: (props?: IconProps) => <FontAwesomeIcon icon={faUsers} {...props} />,
  User: (props?: IconProps) => <FontAwesomeIcon icon={faUser} {...props} />,
  Prev: (props?: IconProps) => <FontAwesomeIcon icon={faBackward} {...props} />,
  Next: (props?: IconProps) => <FontAwesomeIcon icon={faForward} {...props} />,
  Play: (props?: IconProps) => <FontAwesomeIcon icon={faPlay} {...props} />,
  Pause: (props?: IconProps) => <FontAwesomeIcon icon={faPause} {...props} />,
  Image: (props?: IconProps) => <FontAwesomeIcon icon={faImage} {...props} />,
  ChevronDown: (props?: IconProps) => <FontAwesomeIcon icon={faAngleDown} {...props} />,
  ChevronRight: (props?: IconProps) => <FontAwesomeIcon icon={faAngleRight} {...props} />,
  Volume: (props?: IconProps) => <FontAwesomeIcon icon={faVolumeHigh} {...props} />,
  List: (props?: IconProps) => <FontAwesomeIcon icon={faList} {...props} />,
  Mute: (props?: IconProps) => <FontAwesomeIcon icon={faVolumeXmark} {...props} />,
  VolLow: (props?: IconProps) => <FontAwesomeIcon icon={faVolumeLow} {...props} />,
  Shuffle: (props?: IconProps) => <FontAwesomeIcon icon={faShuffle} {...props} />,
  Share: (props?: IconProps) => <FontAwesomeIcon icon={faShareFromSquare} {...props} />,
  Trash: (props?: IconProps) => <FontAwesomeIcon icon={faTrash} {...props} />,
  ArrowUp: (props?: IconProps) => <FontAwesomeIcon icon={faArrowUp} {...props} />,
  CheckCircle: (props?: IconProps) => <FontAwesomeIcon icon={faCircleCheck} {...props} />,
  CheckCircleOutline: (props?: IconProps) => <FontAwesomeIcon icon={faCircleCheck} {...props} />,
  Spinner: (props?: IconProps) => <FontAwesomeIcon icon={faCircleNotch} spin {...props} />,
  TimesCircle: (props?: IconProps) => <FontAwesomeIcon icon={faCircleXmark} {...props} />,
  TimesCircleOutline: (props?: IconProps) => <FontAwesomeIcon icon={faCircleXmark} {...props} />,
  Search: (props?: IconProps) => <FontAwesomeIcon icon={faMagnifyingGlass} {...props} />,
  Plus: (props?: IconProps) => <FontAwesomeIcon icon={faPlus} {...props} />,
  Edit: (props?: IconProps) => <FontAwesomeIcon icon={faPenToSquare} {...props} />,
  ExclamationTriangle: (props?: IconProps) => <FontAwesomeIcon icon={faTriangleExclamation} {...props} />,
  ArrowLeft: (props?: IconProps) => <FontAwesomeIcon icon={faArrowLeft} {...props} />,
  ExclamationCircle: (props?: IconProps) => <FontAwesomeIcon icon={faCircleExclamation} {...props} />,
};
  
